{{- if .Values.autoscaler.enabled }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "App.fullname" }}-hpa
  labels:
{{- include "App.common.labels" | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "App.fullname" }}
  minReplicas: {{ .Values.autoscaler.replicas.min }}
  maxReplicas: {{ .Values.autoscaler.replicas.max }}
  metrics:
    {{- if .Values.autoscaler.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaler.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
